#!/usr/bin/env bash
# Mint the stack's shared secrets into ./.env — the rotation path off the
# throwaway compose defaults (gwk-demo / spine-dev-insecure).
#
#   GATEWAY_CLIENT_KEYS   caller key for BOTH client routes (/v1/messages and
#                         /v1/chat/completions); the control plane's harness
#                         presents it as AIRTRAFFIC_GATEWAY_KEY, so the two
#                         must match.
#   AIRTRAFFIC_SPINE_KEY  shared key on the control plane's gateway spine
#                         routes (leaks / enforcement / patterns).
#   AIRTRAFFIC_ADMIN_KEY  operator key on every state-changing control-plane
#                         route (adapters, policies, credentials, harness) and
#                         the alternative to loopback for keystore admin.
#                         Unset leaves those routes OPEN — the posture the repo
#                         shipped with, warned about at boot. Once set, paste it
#                         into the SPA's "Operator key" field or the consoles
#                         will 401 on every change.
#
# docker compose reads .env automatically. Idempotent: an existing key is kept
# unless --rotate is passed. No real vendor credential is ever written here —
# ANTHROPIC_UPSTREAM_KEY stays the synthetic dev value, and HF_UPSTREAM_TOKEN
# stays unset (its route 502s rather than sending a placeholder to a real
# vendor), until you set them yourself.
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".env"
ROTATE=0
[[ "${1:-}" == "--rotate" ]] && ROTATE=1

gen() { openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

# read_existing NAME → current value in .env, empty if absent
read_existing() {
  [[ -f "$ENV_FILE" ]] || return 0
  sed -n "s/^$1=//p" "$ENV_FILE" | tail -n1
}

set_key() {
  local name="$1" prefix="$2" current
  current="$(read_existing "$name")"
  if [[ -n "$current" && $ROTATE -eq 0 ]]; then
    echo "  $name: kept (pass --rotate to replace)"
    return
  fi
  local value="$prefix$(gen)"
  if [[ -n "$current" ]]; then
    # portable in-place edit (BSD + GNU sed disagree on -i)
    grep -v "^$name=" "$ENV_FILE" >"$ENV_FILE.tmp" && mv "$ENV_FILE.tmp" "$ENV_FILE"
    echo "  $name: rotated"
  else
    echo "  $name: generated"
  fi
  printf '%s=%s\n' "$name" "$value" >>"$ENV_FILE"
}

if [[ ! -f "$ENV_FILE" ]]; then
  printf '# Generated by scripts/dev-env.sh — never commit this file.\n' >"$ENV_FILE"
fi

echo "Writing $ENV_FILE:"
set_key GATEWAY_CLIENT_KEYS gwk-
set_key AIRTRAFFIC_SPINE_KEY spk-
set_key AIRTRAFFIC_ADMIN_KEY adm-
chmod 600 "$ENV_FILE"

cat <<'EOF'

Done. Next:
  docker compose up -d --build          # picks .env up automatically
  grep GATEWAY_CLIENT_KEYS .env         # the key Claude Code / curl must send
  grep AIRTRAFFIC_ADMIN_KEY .env        # paste into the SPA's "Operator key" field

Running the binaries directly? Export the same values:
  set -a; source .env; set +a
EOF
